### ISSUE TITLE
Does not works with lower case flavor names

### ISSUE THREAD

**Issue by xanscale** [nikialeksey/porflavor#1]
... something like this

```
    productFlavors {
        brand1 {
            dimension 'brand'
        }
        brand2 {
            dimension 'brand'
        }
        brand3 {
            dimension 'brand'
        }
        store {
            dimension 'version'
        }
        staging {
            dimension 'version'
        }
    }
```

and using title case flavor name break dependencies implementation flavor specific like that:
```
dependencies {
    storeImplementation ....
    stagingImplementation ....
}
```

**Comment by nikialeksey** [comment]
Can you try new version `0.0.3`? I just added support of lower case flavor names

**Comment by xanscale** [comment]
i will try

**Comment by xanscale** [comment]
works perfectly

**Comment by nikialeksey** [comment]
Nice! Thanks.

**Comment by xanscale** [comment]
@nikialeksey thanks so much, just one useless thing: to put `apply plugin: 'com.nikialeksey.porflavor'` in the middle of the file is quite orrible, there is no way to put that in the start ?

**Comment by nikialeksey** [comment]
@xanscale I have not tried yet. Can you start a new issue, please?
