### ISSUE TITLE
default buildConfigField for non-specific combinations

### ISSUE THREAD

**Issue by lucanicoletti** [nikialeksey/porflavor#10]
In our app we currently have 6 `productFlavors`
```kotlin
productFlavors {
    create("local") {} // the first three are dimension `environment`
    create("staging") {}
    create("production") {}
    create("type1") {} // this and the following are dimension `app`
    create("type2") {}
    create("type3") {}
    create("type4") {}
 }
 ```
 
 Then inside the `porflavor` block, we specify for only a few combinations some BuildConfigFields:
 ```kotlin
 porflavor {
    create("localType1") { 
        buildConfigField("String", "CLIENT_ID", """"id"""")
     }
    create("stagingType1") { 
        buildConfigField("String", "CLIENT_ID", """"id"""")
     }
    create("stagingType2") { 
        buildConfigField("String", "CLIENT_ID", """"id"""")
     }
    create("stagingType3") { 
        buildConfigField("String", "CLIENT_ID", """"id"""")
     }
    create("productionType2") { 
        buildConfigField("String", "CLIENT_ID", """"id"""")
     }
}
```

But for some of the combinations possible, some of the `buildConfigField` are missing, and when selecting one of the lacking `BuildVariants` from Android Studio, or when running the generic `./gradlew build` (which I'm trying to setup on CI, the builds fail as there is no `BuildConfig.CLIENT_ID` specified.

Should I specify all the `BuildConfigField` for every possible combination?

**Comment by lucanicoletti** [comment]
Defining `buildConfigFielf()` in the `defaultConfig` block solves the builds problem! :)

**Comment by nikialeksey** [comment]
Yeah, you are right! `defaultConfig` exists exactly for that. And you can override default config in flavors. If you don't want to define default config, than you have to define this field for all flavors.
