### ISSUE TITLE
Add support for resValue fields

### ISSUE THREAD

**Issue by bogdanzurac** [nikialeksey/porflavor#4]
Currently the library only supports `buildConfigField`s, which are useful for runtime use-cases. It would be great to also support `resValue` fields, since those can be used directly inside the `AndroidManifest`  at compile time.

http://dcow.io/android-gradle-plugin-docs/com/android/build/gradle/api/BaseVariant.html#resValue(java.lang.String,%20java.lang.String,%20java.lang.String)

**Comment by nikialeksey** [comment]
Thanks for the issue! You may try a [new `porflavor` version `0.1.0`](https://plugins.gradle.org/plugin/com.nikialeksey.porflavor) with supporting `resValue` fields

**Comment by bogdanzurac** [comment]
Can confirm it works like a charm, thanks a lot! 🤗
